# Generated by Django 3.2.11 on 2022-10-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='NAME')),
                ('sale_opportunity', models.BooleanField(default=True, verbose_name='Sale Opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True, verbose_name='NAME')),
                ('color', models.CharField(choices=[('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('GRAY', 'GRAY')], max_length=15, verbose_name='COLOR')),
                ('model', models.CharField(choices=[('HATCH', 'HATCH'), ('SEDAN', 'SEDAN'), ('CONVERTIBLE', 'CONVERTIBLE')], max_length=15, verbose_name='MODEL')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owner')),
            ],
        ),
    ]
